### ISSUE TITLE
Blessing of Wisdom

### ISSUE THREAD

**Issue by boyntonj** [AmsTaFFix/gmr-stuff#2]
Currently, the plugin only supports Blessing of Kings/Blessing of Might -- for instances where a user would prefer not to use Judgement of Wisdom, the option to use Blessing of Wisdom would be useful.

**Comment by AmsTaFFix** [comment]
added in [this commit](https://github.com/AmsTaFFix/gmr-stuff/commit/38cc8242b018aea696d7b8a4d9e759f8e288f299)
