### ISSUE TITLE
Add death strike usage in frost rotation

### ISSUE THREAD

**Issue by Kibgc** [AmsTaFFix/gmr-stuff#8]
Hi! Is it possible to add death strike usage in the frost loader? Something like the code from the blood rotation would be great!
Right now my kill speed is faster in frost, but overall clear speed suffer from downtime due to recovery using food. In blood spec its never any downtime.

 ---Min HP to start using Death Strike more often
    useDeathStrikeMoreOftenMinHP = 90,

**Comment by AmsTaFFix** [comment]
added that feature in https://github.com/AmsTaFFix/gmr-stuff/commit/321abc6eba6d582ae60e9f013fdd09cfd837a4d3
